export const DEVINTERVIEW_REPOS = [
  // Languages
  { id: 'javascript', name: 'JavaScript', slug: 'javascript-interview-questions', category: 'Languages' },
  { id: 'python', name: 'Python', slug: 'python-interview-questions', category: 'Languages' },
  { id: 'java', name: 'Java', slug: 'java-interview-questions', category: 'Languages' },
  { id: 'typescript', name: 'TypeScript', slug: 'typescript-interview-questions', category: 'Languages' },
  { id: 'cpp', name: 'C++', slug: 'cpp-interview-questions', category: 'Languages' },
  { id: 'c-sharp', name: 'C#', slug: 'c-sharp-interview-questions', category: 'Languages' },
  { id: 'golang', name: 'Go', slug: 'golang-interview-questions', category: 'Languages' },
  { id: 'rust', name: 'Rust', slug: 'rust-interview-questions', category: 'Languages' },
  { id: 'php', name: 'PHP', slug: 'php-interview-questions', category: 'Languages' },
  { id: 'ruby', name: 'Ruby', slug: 'ruby-interview-questions', category: 'Languages' },
  // { id: 'swift', name: 'Swift', slug: 'swift-interview-questions', category: 'Languages' },
  // { id: 'kotlin', name: 'Kotlin', slug: 'kotlin-interview-questions', category: 'Languages' },
  // { id: 'scala', name: 'Scala', slug: 'scala-interview-questions', category: 'Languages' },
  // { id: 'r', name: 'R', slug: 'r-interview-questions', category: 'Languages' },
  // { id: 'julia', name: 'Julia', slug: 'julia-interview-questions', category: 'Languages' },
  // { id: 'matlab', name: 'MATLAB', slug: 'matlab-interview-questions', category: 'Languages' },
  // { id: 'objective-c', name: 'Objective-C', slug: 'objective-c-interview-questions', category: 'Languages' },

  // Frontend
  { id: 'react', name: 'React', slug: 'react-interview-questions', category: 'Frontend' },
  { id: 'angular', name: 'Angular', slug: 'angular-interview-questions', category: 'Frontend' },
  { id: 'vue', name: 'Vue.js', slug: 'vue-interview-questions', category: 'Frontend' },
  { id: 'angular-js', name: 'AngularJS', slug: 'angular-js-interview-questions', category: 'Frontend' },
  { id: 'next', name: 'Next.js', slug: 'next-interview-questions', category: 'Frontend' },
  { id: 'redux', name: 'Redux', slug: 'redux-interview-questions', category: 'Frontend' },
  { id: 'html5', name: 'HTML5', slug: 'html5-interview-questions', category: 'Frontend' },
  { id: 'css', name: 'CSS', slug: 'css-interview-questions', category: 'Frontend' },
  { id: 'jquery', name: 'jQuery', slug: 'jquery-interview-questions', category: 'Frontend' },
  { id: 'pwa', name: 'PWA', slug: 'pwa-interview-questions', category: 'Frontend' },

  // Backend
  { id: 'node', name: 'Node.js', slug: 'node-interview-questions', category: 'Backend' },
  { id: 'express', name: 'Express', slug: 'express-interview-questions', category: 'Backend' },
  { id: 'django', name: 'Django', slug: 'django-interview-questions', category: 'Backend' },
  { id: 'laravel', name: 'Laravel', slug: 'laravel-interview-questions', category: 'Backend' },
  { id: 'spring', name: 'Spring', slug: 'spring-interview-questions', category: 'Backend' },
  { id: 'ruby-on-rails', name: 'Ruby on Rails', slug: 'ruby-on-rails-interview-questions', category: 'Backend' },
  { id: 'asp-net', name: 'ASP.NET', slug: 'asp-net-interview-questions', category: 'Backend' },
  { id: 'asp-net-mvc', name: 'ASP.NET MVC', slug: 'asp-net-mvc-interview-questions', category: 'Backend' },
  { id: 'asp-net-web-api', name: 'ASP.NET Web API', slug: 'asp-net-web-api-interview-questions', category: 'Backend' },
  { id: 'net-core', name: '.NET Core', slug: 'net-core-interview-questions', category: 'Backend' },

  // Mobile
  // { id: 'react-native', name: 'React Native', slug: 'react-native-interview-questions', category: 'Mobile' },
  // { id: 'flutter', name: 'Flutter', slug: 'flutter-interview-questions', category: 'Mobile' },
  // { id: 'android', name: 'Android', slug: 'android-interview-questions', category: 'Mobile' },
  // { id: 'ionic', name: 'Ionic', slug: 'ionic-interview-questions', category: 'Mobile' },
  // { id: 'xamarin', name: 'Xamarin', slug: 'xamarin-interview-questions', category: 'Mobile' },
  // { id: 'wpf', name: 'WPF', slug: 'wpf-interview-questions', category: 'Mobile' },

  // Database
  { id: 'sql', name: 'SQL', slug: 'sql-interview-questions', category: 'Database' },
  { id: 't-sql', name: 'T-SQL', slug: 't-sql-interview-questions', category: 'Database' },
  { id: 'nosql', name: 'NoSQL', slug: 'nosql-interview-questions', category: 'Database' },
  { id: 'mongodb', name: 'MongoDB', slug: 'mongodb-interview-questions', category: 'Database' },
  { id: 'redis', name: 'Redis', slug: 'redis-interview-questions', category: 'Database' },
  { id: 'cosmos-db', name: 'Cosmos DB', slug: 'cosmos-db-interview-questions', category: 'Database' },
  { id: 'databases', name: 'Databases', slug: 'databases-interview-questions', category: 'Database' },

  // Data Structures
  { id: 'data-structures', name: 'Data Structures', slug: 'data-structures-interview-questions', category: 'Data Structures' },
  { id: 'array', name: 'Array', slug: 'array-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'linked-list', name: 'Linked List', slug: 'linked-list-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'stack', name: 'Stack', slug: 'stack-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'queue', name: 'Queue', slug: 'queue-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'tree', name: 'Tree', slug: 'tree-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'binary-tree', name: 'Binary Tree', slug: 'binary-tree-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'graph', name: 'Graph', slug: 'graph-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'hash-table', name: 'Hash Table', slug: 'hash-table-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'heap-and-map', name: 'Heap & Map', slug: 'heap-and-map-data-structures-interview-questions', category: 'Data Structures' },
  { id: 'trie', name: 'Trie', slug: 'trie-data-structure-interview-questions', category: 'Data Structures' },
  { id: 'string', name: 'String', slug: 'string-data-structure-interview-questions', category: 'Data Structures' },

  // Algorithms
  { id: 'sorting', name: 'Sorting', slug: 'sorting-algorithms-interview-questions', category: 'Algorithms' },
  { id: 'searching', name: 'Searching', slug: 'searching-algorithms-interview-questions', category: 'Algorithms' },
  { id: 'dynamic-programming', name: 'Dynamic Programming', slug: 'dynamic-programming-interview-questions', category: 'Algorithms' },
  { id: 'greedy', name: 'Greedy', slug: 'greedy-algorithms-interview-questions', category: 'Algorithms' },
  { id: 'backtracking', name: 'Backtracking', slug: 'backtracking-algorithms-interview-questions', category: 'Algorithms' },
  { id: 'divide-and-conquer', name: 'Divide & Conquer', slug: 'divide-and-conquer-interview-questions', category: 'Algorithms' },
  { id: 'recursion', name: 'Recursion', slug: 'recursion-algorithm-interview-questions', category: 'Algorithms' },
  { id: 'bit-manipulation', name: 'Bit Manipulation', slug: 'bit-manipulation-interview-questions', category: 'Algorithms' },
  { id: 'genetic-algorithms', name: 'Genetic Algorithms', slug: 'genetic-algorithms-interview-questions', category: 'Algorithms' },
  { id: 'fibonacci', name: 'Fibonacci', slug: 'fibonacci-sequence-interview-questions', category: 'Algorithms' },

  // Machine Learning
  // { id: 'supervised-learning', name: 'Supervised Learning', slug: 'supervised-learning-interview-questions', category: 'Machine Learning' },
  // { id: 'unsupervised-learning', name: 'Unsupervised Learning', slug: 'unsupervised-learning-interview-questions', category: 'Machine Learning' },
  // { id: 'reinforcement-learning', name: 'Reinforcement Learning', slug: 'reinforcement-learning-interview-questions', category: 'Machine Learning' },
  // { id: 'linear-regression', name: 'Linear Regression', slug: 'linear-regression-interview-questions', category: 'Machine Learning' },
  // { id: 'logistic-regression', name: 'Logistic Regression', slug: 'logistic-regression-interview-questions', category: 'Machine Learning' },
  // { id: 'decision-tree', name: 'Decision Tree', slug: 'decision-tree-interview-questions', category: 'Machine Learning' },
  // { id: 'random-forest', name: 'Random Forest', slug: 'random-forest-interview-questions', category: 'Machine Learning' },
  // { id: 'svm', name: 'SVM', slug: 'svm-interview-questions', category: 'Machine Learning' },
  // { id: 'naive-bayes', name: 'Naive Bayes', slug: 'naive-bayes-interview-questions', category: 'Machine Learning' },
  // { id: 'k-nearest-neighbors', name: 'K-Nearest Neighbors', slug: 'k-nearest-neighbors-interview-questions', category: 'Machine Learning' },
  // { id: 'k-means', name: 'K-Means', slug: 'k-means-clustering-interview-questions', category: 'Machine Learning' },
  // { id: 'cluster-analysis', name: 'Cluster Analysis', slug: 'cluster-analysis-interview-questions', category: 'Machine Learning' },
  // { id: 'ensemble-learning', name: 'Ensemble Learning', slug: 'ensemble-learning-interview-questions', category: 'Machine Learning' },
  // { id: 'xgboost', name: 'XGBoost', slug: 'xgboost-interview-questions', category: 'Machine Learning' },
  // { id: 'light-gbm', name: 'LightGBM', slug: 'light-gbm-interview-questions', category: 'Machine Learning' },
  // { id: 'q-learning', name: 'Q-Learning', slug: 'q-learning-interview-questions', category: 'Machine Learning' },
  // { id: 'gradient-descent', name: 'Gradient Descent', slug: 'gradient-descent-interview-questions', category: 'Machine Learning' },
  // { id: 'pca', name: 'PCA', slug: 'pca-interview-questions', category: 'Machine Learning' },
  // { id: 'dimensionality-reduction', name: 'Dimensionality Reduction', slug: 'dimensionality-reduction-interview-questions', category: 'Machine Learning' },
  // { id: 'feature-engineering', name: 'Feature Engineering', slug: 'feature-engineering-interview-questions', category: 'Machine Learning' },
  // { id: 'model-evaluation', name: 'Model Evaluation', slug: 'model-evaluation-interview-questions', category: 'Machine Learning' },
  // { id: 'bias-and-variance', name: 'Bias & Variance', slug: 'bias-and-variance-interview-questions', category: 'Machine Learning' },
  // { id: 'cost-function', name: 'Cost Function', slug: 'cost-function-interview-questions', category: 'Machine Learning' },
  // { id: 'recommendation-systems', name: 'Recommendation Systems', slug: 'recommendation-systems-interview-questions', category: 'Machine Learning' },
  // { id: 'time-series', name: 'Time Series', slug: 'time-series-interview-questions', category: 'Machine Learning' },
  // { id: 'anomaly-detection', name: 'Anomaly Detection', slug: 'anomaly-detection-interview-questions', category: 'Machine Learning' },
  // { id: 'classification', name: 'Classification', slug: 'classification-algorithms-interview-questions', category: 'Machine Learning' },

  // Deep Learning
  // { id: 'deep-learning', name: 'Deep Learning', slug: 'deep-learning-interview-questions', category: 'Deep Learning' },
  // { id: 'neural-networks', name: 'Neural Networks', slug: 'neural-networks-interview-questions', category: 'Deep Learning' },
  // { id: 'cnn', name: 'CNN', slug: 'cnn-interview-questions', category: 'Deep Learning' },
  // { id: 'rnn', name: 'RNN', slug: 'rnn-interview-questions', category: 'Deep Learning' },
  // { id: 'gans', name: 'GANs', slug: 'gans-interview-questions', category: 'Deep Learning' },
  // { id: 'autoencoders', name: 'Autoencoders', slug: 'autoencoders-interview-questions', category: 'Deep Learning' },
  // { id: 'transfer-learning', name: 'Transfer Learning', slug: 'transfer-learning-interview-questions', category: 'Deep Learning' },
  // { id: 'computer-vision', name: 'Computer Vision', slug: 'computer-vision-interview-questions', category: 'Deep Learning' },
  // { id: 'nlp', name: 'NLP', slug: 'nlp-interview-questions', category: 'Deep Learning' },
  // { id: 'llms', name: 'LLMs', slug: 'llms-interview-questions', category: 'Deep Learning' },
  // { id: 'chatgpt', name: 'ChatGPT', slug: 'chatgpt-interview-questions', category: 'Deep Learning' },
  // { id: 'explainable-ai', name: 'Explainable AI', slug: 'explainable-ai-interview-questions', category: 'Deep Learning' },

  // AI/ML Tools
  // { id: 'tensorflow', name: 'TensorFlow', slug: 'tensorflow-interview-questions', category: 'AI/ML Tools' },
  // { id: 'pytorch', name: 'PyTorch', slug: 'pytorch-interview-questions', category: 'AI/ML Tools' },
  // { id: 'keras', name: 'Keras', slug: 'keras-interview-questions', category: 'AI/ML Tools' },
  // { id: 'scikit-learn', name: 'Scikit-learn', slug: 'scikit-learn-interview-questions', category: 'AI/ML Tools' },
  // { id: 'numpy', name: 'NumPy', slug: 'numpy-interview-questions', category: 'AI/ML Tools' },
  // { id: 'pandas', name: 'Pandas', slug: 'pandas-interview-questions', category: 'AI/ML Tools' },
  // { id: 'python-ml', name: 'Python ML', slug: 'python-ml-interview-questions', category: 'AI/ML Tools' },
  // { id: 'sql-ml', name: 'SQL ML', slug: 'sql-ml-interview-questions', category: 'AI/ML Tools' },

  // Cloud & DevOps
  { id: 'aws', name: 'AWS', slug: 'aws-interview-questions', category: 'Cloud & DevOps' },
  { id: 'azure', name: 'Azure', slug: 'azure-interview-questions', category: 'Cloud & DevOps' },
  { id: 'docker', name: 'Docker', slug: 'docker-interview-questions', category: 'Cloud & DevOps' },
  { id: 'kubernetes', name: 'Kubernetes', slug: 'kubernetes-interview-questions', category: 'Cloud & DevOps' },
  { id: 'devops', name: 'DevOps', slug: 'devops-interview-questions', category: 'Cloud & DevOps' },
  { id: 'mlops', name: 'MLOps', slug: 'mlops-interview-questions', category: 'Cloud & DevOps' },
  { id: 'llmops', name: 'LLMOps', slug: 'llmops-interview-questions', category: 'Cloud & DevOps' },

  // Architecture
  { id: 'microservices', name: 'Microservices', slug: 'microservices-interview-questions', category: 'Architecture' },
  { id: 'software-architecture', name: 'Software Architecture', slug: 'software-architecture-interview-questions', category: 'Architecture' },
  { id: 'domain-driven-design', name: 'Domain-Driven Design', slug: 'domain-driven-design-interview-questions', category: 'Architecture' },
  { id: 'service-oriented-architecture', name: 'SOA', slug: 'service-oriented-architecture-interview-questions', category: 'Architecture' },
  { id: 'api-design', name: 'API Design', slug: 'api-design-interview-questions', category: 'Architecture' },
  { id: 'graphql', name: 'GraphQL', slug: 'graphql-interview-questions', category: 'Architecture' },
  { id: 'websocket', name: 'WebSocket', slug: 'websocket-interview-questions', category: 'Architecture' },
  { id: 'reactive-programming', name: 'Reactive Programming', slug: 'reactive-programming-interview-questions', category: 'Architecture' },
  { id: 'reactive-systems', name: 'Reactive Systems', slug: 'reactive-systems-interview-questions', category: 'Architecture' },
  { id: 'layering-and-middleware', name: 'Layering & Middleware', slug: 'layering-and-middleware-interview-questions', category: 'Architecture' },

  // Data Science
  // { id: 'data-scientist', name: 'Data Scientist', slug: 'data-scientist-interview-questions', category: 'Data Science' },
  // { id: 'data-analyst', name: 'Data Analyst', slug: 'data-analyst-interview-questions', category: 'Data Science' },
  // { id: 'data-engineer', name: 'Data Engineer', slug: 'data-engineer-interview-questions', category: 'Data Science' },
  // { id: 'data-mining', name: 'Data Mining', slug: 'data-mining-interview-questions', category: 'Data Science' },
  // { id: 'data-processing', name: 'Data Processing', slug: 'data-processing-interview-questions', category: 'Data Science' },
  // { id: 'apache-spark', name: 'Apache Spark', slug: 'apache-spark-interview-questions', category: 'Data Science' },
  // { id: 'hadoop', name: 'Hadoop', slug: 'hadoop-interview-questions', category: 'Data Science' },

  // Concepts
  { id: 'oop', name: 'OOP', slug: 'oop-interview-questions', category: 'Concepts' },
  { id: 'big-o', name: 'Big O Notation', slug: 'big-o-notation-interview-questions', category: 'Concepts' },
  { id: 'concurrency', name: 'Concurrency', slug: 'concurrency-interview-questions', category: 'Concepts' },
  { id: 'dependency-injection', name: 'Dependency Injection', slug: 'dependency-injection-interview-questions', category: 'Concepts' },
  { id: 'caching', name: 'Caching', slug: 'caching-interview-questions', category: 'Concepts' },
  { id: 'load-balancing', name: 'Load Balancing', slug: 'load-balancing-interview-questions', category: 'Concepts' },
  { id: 'availability-and-reliability', name: 'Availability & Reliability', slug: 'availability-and-reliability-interview-questions', category: 'Concepts' },
  { id: 'cap-theorem', name: 'CAP Theorem', slug: 'cap-theorem-interview-questions', category: 'Concepts' },
  { id: 'optimization', name: 'Optimization', slug: 'optimization-interview-questions', category: 'Concepts' },
  { id: 'probability', name: 'Probability', slug: 'probability-interview-questions', category: 'Concepts' },
  { id: 'statistics', name: 'Statistics', slug: 'statistics-interview-questions', category: 'Concepts' },
  { id: 'linear-algebra', name: 'Linear Algebra', slug: 'linear-algebra-interview-questions', category: 'Concepts' },
  { id: 'curse-of-dimensionality', name: 'Curse of Dimensionality', slug: 'curse-of-dimensionality-interview-questions', category: 'Concepts' },
  { id: 'ml-design-patterns', name: 'ML Design Patterns', slug: 'ml-design-patterns-interview-questions', category: 'Concepts' },

  // Tools
  { id: 'git', name: 'Git', slug: 'git-interview-questions', category: 'Tools' },
  { id: 'entity-framework', name: 'Entity Framework', slug: 'entity-framework-interview-questions', category: 'Tools' },
  { id: 'linq', name: 'LINQ', slug: 'linq-interview-questions', category: 'Tools' },
  { id: 'ado-net', name: 'ADO.NET', slug: 'ado-net-interview-questions', category: 'Tools' },
  { id: 'xml', name: 'XML', slug: 'xml-interview-questions', category: 'Tools' },

  // Testing
  // { id: 'testing', name: 'Testing', slug: 'testing-interview-questions', category: 'Testing' },

  // Security
  { id: 'web-security', name: 'Web Security', slug: 'web-security-interview-questions', category: 'Security' },
  { id: 'cryptography', name: 'Cryptography', slug: 'cryptography-interview-questions', category: 'Security' },
  { id: 'blockchain', name: 'Blockchain', slug: 'blockchain-interview-questions', category: 'Security' },

  // Methodologies
  // { id: 'agile-and-scrum', name: 'Agile & Scrum', slug: 'agile-and-scrum-interview-questions', category: 'Methodologies' },

  // Design
  { id: 'ux-design', name: 'UX Design', slug: 'ux-design-interview-questions', category: 'Design' },
];
